In [1]:
import numpy as np
import matplotlib.pyplot as plt
import torch
from torch import nn

In [2]:
class IrisModel(nn.Module):
    def __init__(self, hidden_layer_neurons=8):
        super().__init__() 
        self.layers = nn.Sequential(
            nn.Linear(in_features=4, out_features=hidden_layer_neurons),
            nn.ReLU(),
            nn.Linear(in_features=hidden_layer_neurons, out_features=hidden_layer_neurons),
            nn.ReLU(),
            nn.Linear(in_features=hidden_layer_neurons, out_features=3)
        )

    def forward(self, x):
        return self.layers(x)

In [3]:
model = IrisModel()

In [6]:
model.load_state_dict(torch.load("iris_model", weights_only=True))

<All keys matched successfully>

In [8]:
model.state_dict()

OrderedDict([('layers.0.weight',
              tensor([[-0.2028,  0.0541, -0.1766, -0.0785],
                      [ 0.2142,  0.2671,  0.5432, -0.1856],
                      [ 0.5726,  0.5681, -0.6973, -0.8732],
                      [-0.1169, -0.3214, -0.0804, -0.0961],
                      [ 0.0600,  0.6509, -0.4523, -0.3739],
                      [ 0.6427,  0.0119,  0.6174, -0.2037],
                      [ 0.4851,  0.8428, -0.7317, -0.9508],
                      [ 0.0259, -0.4893,  0.0479,  0.3432]])),
             ('layers.0.bias',
              tensor([-0.3900, -0.4904,  0.4608, -0.4559,  0.1541, -0.5011,  0.5760, -0.1523])),
             ('layers.2.weight',
              tensor([[ 0.0664,  0.0433, -0.7888,  0.1179, -0.0599,  0.3824, -0.1776,  0.2618],
                      [ 0.1031,  0.1844, -0.1893, -0.3047,  0.1123,  0.5244,  0.1828,  0.1736],
                      [ 0.0522,  0.3353, -0.1464,  0.1759, -0.1838,  0.2561,  0.2432,  0.2326],
                      [-0.2853,  0.