In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [36]:
X = np.array([[-0.5, 0.5]])
y = np.array([[0.4]])

In [37]:
W1 = np.random.random_sample((5, 2)) * 0.01
W2 = np.random.random_sample((1, 5)) * 0.01

In [38]:
epochs = 20
alpha = 0.1
for i in range(epochs):
    h = X @ W1.T
    y_out = h @ W2.T
    error = np.square(y - y_out)
    G2 = - 2 * (y - y_out) * h
    G1 = -2 * (y - y_out) * W2.T @ X
    W1 -= G1
    W2 -= G2

In [39]:
final_h = X @ W1.T
final_y_out = h @ W2.T
final_y_out

array([[0.40000004]])

In [34]:
A = np.array([[1, 2], [3, 4]])
B = np.array([1, 0])

In [40]:
C = B @ A.T

In [54]:
y_out * h

array([[-1.24332145,  3.65231436]])

In [57]:
h

array([[-1.47714111,  4.33917045]])