In [1]:
import numpy as np

In [2]:
graph = {
    "Biratnagar": {"Itahari": 22, "Rangeli": 25, "Biratchowk": 30},
    "Itahari": {"Biratnagar": 22, "Dharan": 20, "Biratchowk": 11},
    "Dharan": {"Itahari": 20},
    "Biratchowk": {"Biratnagar": 30, "Itahari": 11, "Kanepokhari": 10},
    "Kanepokhari": {"Biratchowk": 10, "Rangeli": 25, "Urlabari": 12},
    "Rangeli": {"Biratnagar": 25, "Kanepokhari": 25, "Urlabari": 40},
    "Urlabari": {"Kanepokhari": 12, "Rangeli": 40, "Damak": 6},
    "Damak": {"Urlabari": 6},
}

In [3]:
MAX = 1_000_000
data = []
for city in graph:
    row = []
    for other in graph:
        if (city == other):
            row.append(0)
        else:
            row.append(graph[city].get(other, MAX))
    data.append(row)
data = np.array(data)

In [4]:
data

array([[      0,      22, 1000000,      30, 1000000,      25, 1000000,
        1000000],
       [     22,       0,      20,      11, 1000000, 1000000, 1000000,
        1000000],
       [1000000,      20,       0, 1000000, 1000000, 1000000, 1000000,
        1000000],
       [     30,      11, 1000000,       0,      10, 1000000, 1000000,
        1000000],
       [1000000, 1000000, 1000000,      10,       0,      25,      12,
        1000000],
       [     25, 1000000, 1000000, 1000000,      25,       0,      40,
        1000000],
       [1000000, 1000000, 1000000, 1000000,      12,      40,       0,
              6],
       [1000000, 1000000, 1000000, 1000000, 1000000, 1000000,       6,
              0]])

In [34]:
city_encoding = {key: value for value, key in enumerate(graph.keys())}
city_encoding

{'Biratnagar': 0,
 'Itahari': 1,
 'Dharan': 2,
 'Biratchowk': 3,
 'Kanepokhari': 4,
 'Rangeli': 5,
 'Urlabari': 6,
 'Damak': 7}

## Example

In [262]:
data = [
    [  0,  83,  93, 129, 133, 139, 151, 169, 135, 114, 110,  98,  99,  95,  81, 152, 159, 181, 172, 185, 147, 157, 185, 220, 127, 181],
    [ 83,   0,  40,  53,  62,  64,  91, 116,  93,  84,  95,  98,  89,  68,  67, 127, 156, 175, 152, 165, 160, 180, 223, 268, 179, 197],
    [ 93,  40,   0,  42,  42,  49,  59,  81,  54,  44,  58,  64,  54,  31,  36,  86, 117, 135, 112, 125, 124, 147, 193, 241, 157, 161],
    [129,  53,  42,   0,  11,  11,  46,  72,  65,  70,  88, 100,  89,  66,  76, 102, 142, 156, 127, 139, 155, 180, 228, 278, 197, 190],
    [133,  62,  42,  11,   0,   9,  35,  61,  55,  62,  82,  95,  84,  62,  74,  93, 133, 146, 117, 128, 148, 173, 222, 272, 194, 182],
    [139,  64,  49,  11,   9,   0,  39,  65,  63,  71,  90, 103,  92,  71,  82, 100, 141, 153, 124, 135, 156, 181, 230, 280, 202, 190],
    [151,  91,  59,  46,  35,  39,   0,  26,  34,  52,  71,  88,  77,  63,  78,  66, 110, 119,  88,  98, 130, 156, 206, 257, 188, 160],
    [169, 116,  81,  72,  61,  65,  26,   0,  37,  59,  75,  92,  83,  76,  91,  54,  98, 103,  70,  78, 122, 148, 198, 250, 188, 148],
    [135,  93,  54,  65,  55,  63,  34,  37,   0,  22,  39,  56,  47,  40,  55,  37,  78,  91,  62,  74,  96, 122, 172, 223, 155, 128],
    [114,  84,  44,  70,  62,  71,  52,  59,  22,   0,  20,  36,  26,  20,  34,  43,  74,  91,  68,  82,  86, 111, 160, 210, 136, 121],
    [110,  95,  58,  88,  82,  90,  71,  75,  39,  20,   0,  18,  11,  27,  32,  42,  61,  80,  64,  77,  68,  92, 140, 190, 116, 103],
    [ 98,  98,  64, 100,  95, 103,  88,  92,  56,  36,  18,   0,  11,  34,  31,  56,  63,  85,  75,  87,  62,  83, 129, 178, 100,  99],
    [ 99,  89,  54,  89,  84,  92,  77,  83,  47,  26,  11,  11,   0,  23,  24,  53,  68,  89,  74,  87,  71,  93, 140, 189, 111, 107],
    [ 95,  68,  31,  66,  62,  71,  63,  76,  40,  20,  27,  34,  23,   0,  15,  62,  87, 106,  87, 100,  93, 116, 163, 212, 132, 130],
    [ 81,  67,  36,  76,  74,  82,  78,  91,  55,  34,  32,  31,  24,  15,   0,  73,  92, 112,  96, 109,  93, 113, 158, 205, 122, 130],
    [152, 127,  86, 102,  93, 100,  66,  54,  37,  43,  42,  56,  53,  62,  73,   0,  44,  54,  26,  39,  68,  94, 144, 196, 139,  95],
    [159, 156, 117, 142, 133, 141, 110,  98,  78,  74,  61,  63,  68,  87,  92,  44,   0,  22,  34,  38,  30,  53, 102, 154, 109,  51],
    [181, 175, 135, 156, 146, 153, 119, 103,  91,  91,  80,  85,  89, 106, 112,  54,  22,   0,  33,  29,  46,  64, 107, 157, 125,  51],
    [172, 152, 112, 127, 117, 124,  88,  70,  62,  68,  64,  75,  74,  87,  96,  26,  34,  33,   0,  13,  63,  87, 135, 186, 141,  81],
    [185, 165, 125, 139, 128, 135,  98,  78,  74,  82,  77,  87,  87, 100, 109,  39,  38,  29,  13,   0,  68,  90, 136, 186, 148,  79],
    [147, 160, 124, 155, 148, 156, 130, 122,  96,  86,  68,  62,  71,  93,  93,  68,  30,  46,  63,  68,   0,  26,  77, 128,  80,  37],
    [157, 180, 147, 180, 173, 181, 156, 148, 122, 111,  92,  83,  93, 116, 113,  94,  53,  64,  87,  90,  26,   0,  50, 102,  65,  27],
    [185, 223, 193, 228, 222, 230, 206, 198, 172, 160, 140, 129, 140, 163, 158, 144, 102, 107, 135, 136,  77,  50,   0,  51,  64,  58],
    [220, 268, 241, 278, 272, 280, 257, 250, 223, 210, 190, 178, 189, 212, 205, 196, 154, 157, 186, 186, 128, 102,  51,   0,  93, 107],
    [127, 179, 157, 197, 194, 202, 188, 188, 155, 136, 116, 100, 111, 132, 122, 139, 109, 125, 141, 148,  80,  65,  64,  93,   0,  90],
    [181, 197, 161, 190, 182, 190, 160, 148, 128, 121, 103,  99, 107, 130, 130,  95,  51,  51,  81,  79,  37,  27,  58, 107,  90,   0]
]

In [263]:
populations = np.array([np.random.permutation(len(data)) for _ in range(10)])

In [264]:
populations

array([[ 1,  4, 16,  3, 24, 18, 23, 15,  8,  7,  9,  2, 12, 11, 20,  0,
        10, 13, 17, 22, 25, 19,  5, 21,  6, 14],
       [18, 23, 16,  1,  4, 11,  8, 15, 12,  5, 21, 13,  0, 17, 24, 10,
         3,  9, 25, 22, 19, 20,  7,  2, 14,  6],
       [ 9,  0, 17, 12, 11, 24, 18, 20, 13,  8, 14, 15,  7,  3,  5, 21,
        19,  2,  1,  6, 10,  4, 23, 25, 22, 16],
       [21, 16, 25, 18, 20,  9, 13,  6, 19,  1,  3, 14, 24, 10, 23, 22,
         8,  2,  7, 12,  5,  0,  4, 17, 15, 11],
       [ 9,  7,  0, 17, 22, 15, 12,  2,  5, 23,  6, 19, 16, 10, 20, 14,
        24,  3, 13,  8, 25, 21, 18, 11,  4,  1],
       [13, 11, 24, 15,  9, 25, 22,  7, 10, 12, 19,  0, 20, 16,  8,  3,
        14,  6, 23, 17, 18,  5, 21,  1,  2,  4],
       [ 8,  5, 13, 12, 21, 10, 23, 22, 19,  6, 11, 18,  2,  9,  4,  1,
        15, 25, 16, 20,  0, 24, 17, 14,  3,  7],
       [14, 13, 17, 15,  7, 12,  5,  4,  9,  2,  8, 23, 11, 18, 16, 25,
        10, 24, 20, 19,  6,  1,  0,  3, 22, 21],
       [22, 14, 24,  4, 15, 12, 

In [265]:
def fitness(indi):
    cost = 0
    for curr, nex in zip(indi[:-1], indi[1:]):
        cost += data[curr][nex]
    return cost + data[indi[-1]][indi[0]]

In [266]:
def crossover(p1: np.ndarray, p2: np.ndarray):
    o1 = p1.copy()
    o2 = p2.copy()
    S_no = np.random.randint(p1.size//2 - 1, p1.size//2 + 2)
    S_ind = np.random.choice(p1.size, S_no, replace=False)
    S_prime_ind = np.setdiff1d(np.arange(p1.size), S_ind)
    o1[S_ind] = p1[S_ind]
    o1[S_prime_ind] = p2[~np.isin(p2, p1[S_ind])]
    o2[S_ind] = p2[S_ind]
    o2[S_prime_ind] = p1[~np.isin(p1, p2[S_ind])]
    return o1, o2

In [281]:
def mutation(indi):
    swap = np.random.choice(indi.size, 2)
    indi[swap] = indi[swap[::-1]]

In [267]:
crossover(populations[0], populations[1])

(array([ 1, 16,  4,  3, 24, 18, 23, 11,  8,  7, 15,  2, 12, 21, 20,  0, 10,
        13, 17,  9, 25, 22,  5, 19, 14,  6]),
 array([18, 16, 23,  1,  4, 11,  8, 15,  2,  5, 12, 13, 20,  0, 24, 10,  3,
         9, 17, 22, 25, 19,  7, 21,  6, 14]))

In [268]:
np.argsort([fitness(x) for x in populations])

array([6, 7, 3, 2, 9, 5, 0, 1, 4, 8])

In [269]:
for x in populations:
    print(f"individual: {x}, fitness: {fitness(x)}")

individual: [ 1  4 16  3 24 18 23 15  8  7  9  2 12 11 20  0 10 13 17 22 25 19  5 21
  6 14], fitness: 2612
individual: [18 23 16  1  4 11  8 15 12  5 21 13  0 17 24 10  3  9 25 22 19 20  7  2
 14  6], fitness: 2651
individual: [ 9  0 17 12 11 24 18 20 13  8 14 15  7  3  5 21 19  2  1  6 10  4 23 25
 22 16], fitness: 2390
individual: [21 16 25 18 20  9 13  6 19  1  3 14 24 10 23 22  8  2  7 12  5  0  4 17
 15 11], fitness: 2381
individual: [ 9  7  0 17 22 15 12  2  5 23  6 19 16 10 20 14 24  3 13  8 25 21 18 11
  4  1], fitness: 2694
individual: [13 11 24 15  9 25 22  7 10 12 19  0 20 16  8  3 14  6 23 17 18  5 21  1
  2  4], fitness: 2601
individual: [ 8  5 13 12 21 10 23 22 19  6 11 18  2  9  4  1 15 25 16 20  0 24 17 14
  3  7], fitness: 2259
individual: [14 13 17 15  7 12  5  4  9  2  8 23 11 18 16 25 10 24 20 19  6  1  0  3
 22 21], fitness: 2293
individual: [22 14 24  4 15 12 20  1  9  6 13  0 17 16  8 23 25  7 10 11 19  5 21  3
 18  2], fitness: 3012
individual: [18  7 25 24 13 

In [310]:
def tournament_selection(populations, fitness_scores, tournament_size=3):
    tournament_idx = np.random.choice(len(populations), tournament_size)
    tournament_fitness = [fitness_scores[i] for i in tournament_idx]
    winner_idx = tournament_idx[np.argmin(tournament_fitness)]  # min for TSP
    return populations[winner_idx]

In [312]:
def elitism(populations, fitness_scores, num_elite=2):
    elite_idx = np.argsort(fitness_scores)[:num_elite]
    return populations[elite_idx]

In [313]:
def adaptive_mutation_rate(gen, max_gen, initial_rate=0.001, final_rate=0.0001):
    return initial_rate - (initial_rate - final_rate) * (gen / max_gen)

In [316]:
def genetic_algorithm(max_generations=1000, population_size=100, elite_size=2):
    best_solution = None
    best_fitness = float('inf')
    populations = np.array([np.random.permutation(len(data)) for _ in range(population_size)])    
    
    for gen in range(max_generations):
        # Calculate fitness for entire population
        population_fitness = np.array([fitness(x) for x in populations])
        current_mean_fitness = np.mean(population_fitness)
        
        # Store best solution
        gen_best_idx = np.argmin(population_fitness)
        gen_best_fitness = population_fitness[gen_best_idx]
        if gen_best_fitness < best_fitness:
            best_fitness = gen_best_fitness
            best_solution = populations[gen_best_idx].copy()
        
        # Early stopping
        if best_fitness < 1000:
            break
            
        # Elitism - preserve best solutions
        elite_solutions = elitism(populations, population_fitness, elite_size)
        
        # Create new population
        new_populations = np.zeros_like(populations)
        new_populations[:elite_size] = elite_solutions
        
        # Fill rest of population with crossover and mutation
        for i in range(elite_size, population_size, 2):
            # Tournament selection
            parent1 = tournament_selection(populations, population_fitness)
            parent2 = tournament_selection(populations, population_fitness)
            
            # Crossover
            offspring1, offspring2 = crossover(parent1, parent2)
            
            # Adaptive mutation
            mutation_rate = adaptive_mutation_rate(gen, max_generations)
            if np.random.random() < mutation_rate:
                mutation(offspring1)
            if np.random.random() < mutation_rate:
                mutation(offspring2)
                
            new_populations[i] = offspring1
            if i + 1 < population_size:
                new_populations[i + 1] = offspring2
        
        populations = new_populations
        
        # Logging
        if gen % 10 == 0:  # Print every 10 generations
            print(f"Generation: {gen}")
            print(f"Best Fitness: {best_fitness}")
            print(f"Mean Fitness: {current_mean_fitness}")
            print(f"Best Solution: {best_solution}")
            print("---")
    
    return best_solution, best_fitness

In [318]:
soln, cost = genetic_algorithm(population_size=200)

Generation: 0
Best Fitness: 1918
Mean Fitness: 2695.69
Best Solution: [22 23 19 18 10 25 15  4  6  3  1  2 14 11  9 20 12 16 13  8 17  7  5  0
 21 24]
---
Generation: 10
Best Fitness: 1785
Mean Fitness: 2476.585
Best Solution: [11 13  3  0 16 25 21 24 23 22 17  1  6  7 18 15  9 12 20 19  5  4 14  2
 10  8]
---
Generation: 20
Best Fitness: 1536
Mean Fitness: 2076.82
Best Solution: [17 20 21 25 22 24 23 10 16 15  5  4  2  3  1  0 13 14 11  7  6 18 19  8
 12  9]
---
Generation: 30
Best Fitness: 1448
Mean Fitness: 1869.415
Best Solution: [16 20 22 23 24 21 25  0 10 11  4  3  5  7  9 13  1  2 14  6  8 18 19 17
 15 12]
---
Generation: 40
Best Fitness: 1204
Mean Fitness: 1453.07
Best Solution: [17 16 20 25 21 23 22 24  0  1 13  2  3  5  4  6  9 14 10  8  7 11 12 18
 15 19]
---


In [320]:
soln

array([17, 16, 20, 21, 25, 22, 23, 24,  0,  1,  2,  5,  3,  4,  6,  7,  9,
        8, 13, 14, 11, 12, 10, 15, 18, 19])

In [308]:
for gen in range(1000):
    population_fitness = np.array([fitness(x) for x in populations])
    population_mean_fitness = np.mean(population_fitness)
    fitness_sorted_indexes = np.argsort(population_fitness)
    # normalized_fitness = population_fitness / np.sum(population_fitness)
    # expected_count = normalized_fitness * len(populations)
    populations = populations[fitness_sorted_indexes]
    best_fit = population_fitness[fitness_sorted_indexes[0]]
    print(
        "\nGeneration: ", gen,
        "\nFitness: ", population_fitness,
        "\nMean Poulation Fitness: ", population_mean_fitness,
        # "\nNormalized Fitness: ", normalized_fitness,
        # "\nExpected count: ", expected_count
        "\nBest Individual: ", populations[0],
        "Best Fitness: ", best_fit
    )
    if (best_fit < 1000):
        break
    for i in range(0, len(populations), 2):
        p1 = populations[i]
        p2 = populations[i+1]
        o1, o2 = crossover(p1, p2)
        if np.random.random_sample() < 0.001:
            mutation(o1)
        if np.random.random_sample() < 0.001:
            mutation(o2)
        populations[i] = o1
        populations[i+1] = o2


Generation:  0 
Fitness:  [2379 2835 2562 2507 2323 3036 2778 2542 2644 2838] 
Mean Poulation Fitness:  2644.4 
Best Individual:  [16 10 24 20 23  9  1  6  8  0 15 25 19  2  4  5 18 13 11  3  7 17 22 21
 14 12] Best Fitness:  2323

Generation:  1 
Fitness:  [2898 2421 2590 2723 2082 2414 2880 2840 2709 2924] 
Mean Poulation Fitness:  2648.1 
Best Individual:  [ 1  8 13  0  9 18 24 20 23 10 25 19 11  4  5  2 15  7 17 16 22 21 12 14
  6  3] Best Fitness:  2082

Generation:  2 
Fitness:  [2246 2420 2511 2747 2682 2523 2347 2882 2886 2533] 
Mean Poulation Fitness:  2577.7 
Best Individual:  [ 1 20 13  0  9  8  6 11 23 18 10 25 24  4  5  2 15  7 17 16 19 21 22 14
 12  3] Best Fitness:  2246

Generation:  3 
Fitness:  [2985 2675 2492 2993 2645 2716 2687 2890 2783 2868] 
Mean Poulation Fitness:  2773.4 
Best Individual:  [23 20  9 13  8  1 18 10  0 25  4  5  2 11 24  7 16 15 19 17 14 21 22 12
  6  3] Best Fitness:  2492

Generation:  4 
Fitness:  [2691 2963 2826 2625 2742 2899 2571 2970 2773

In [278]:
swap = np.array([1, 4])
a = np.array([1, 2, 3, 4, 5])

In [279]:
a[swap] = a[swap[::-1]]

In [305]:
np.random.random_sample()

0.17791169784616068